* https://jovian.ai/aakashns/01-pytorch-basics

In [1]:
import torch
print(torch.__version__)
import numpy as np

1.10.0


### tensor objects

In [5]:
t1=torch.tensor(4.)
print(t1)
print(t1.dtype)
print(t1.shape)

tensor(4.)
torch.float32
torch.Size([])


In [6]:
t2=torch.tensor([1.,2,3,4]) # letting one element to be float, all elements become float.
print(t2)
print(t2.dtype)
print(t2.shape)

tensor([1., 2., 3., 4.])
torch.float32
torch.Size([4])


In [7]:
t3=torch.tensor(
[[5.,6],
[7, 8],
[9,10]]  ) 
print(t3)
print(t3.dtype)
print(t3.shape)

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
torch.float32
torch.Size([3, 2])


In [8]:
t4=torch.tensor([
  [[11.,12,13],
  [13,14,15 ]],
  [[15,16,17],
  [17,18,19]]
] )
print(t4)
print(t4.dtype)
print(t4.shape)

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])
torch.float32
torch.Size([2, 2, 3])


* Indexing is a little confusing, since it is different from R.
The reading order is which matrix > which row > which column.

In [9]:
print(t4[0,:,:]) # indexing is different from R.
print(t4[:,0,:]) # which matrix > which row > which column
print(t4[:,:,0])
print(t4[1,1,1])

tensor([[11., 12., 13.],
        [13., 14., 15.]])
tensor([[11., 12., 13.],
        [15., 16., 17.]])
tensor([[11., 13.],
        [15., 17.]])
tensor(18.)


In [10]:
x = torch.empty(4,2,3)
print(x)

tensor([[[1.3563e-19, 4.5156e+27, 1.8529e+28],
         [1.8037e+28, 4.6894e+27, 7.2251e+28]],

        [[1.3556e-19, 4.8948e+30, 1.6534e+19],
         [6.7421e+22, 1.5766e-19, 1.1578e+27]],

        [[1.3563e-19, 1.3563e-19, 1.8311e+25],
         [5.0832e+31, 1.2119e+25, 1.8611e+34]],

        [[2.0283e-19, 7.1449e+31, 2.6301e+20],
         [7.1833e+22, 1.1704e-19, 7.3845e+20]]])


* We can convert np.array into torch.tensor.
* Although they look the same, torch.tensor can pull off greater things, including autogradient and GPU operations.

In [11]:
x=np.array(
[[1.,2],
[3,4]])
x
y=torch.from_numpy(x)
print(x.dtype) # numpy data
print(y.dtype) # torch data

float64
torch.float64


### indicing & reshape(-1, .. )

* A tensor object with shape = (d1, d2, d3) means that the tensor object is a 3-d array, with 1st-size=d1, 2nd-size=d2, 3rd-size=d3.
* There are three layers of brackets. most outer layer bracket: 1 / second outer layer bracket: d1 / third outer layer (or the most inner layter) bracket: d2 / number of elements in the most inner bracket: d3.
* We can observe that obj has 2 matrices with two brackets [[]]. $\rightarrow$ d1=2
* Each 1st element contains 3 objects with one bracket []. $\rightarrow$ d2=3.
* Each 2nd element contains 4 elements. $\rightarrow$ d3=4.
* So the shape of the obj is torch.Size(2,3,4).

* matrix (d1, d2) : d1-by-d2 matrix
* 3-d array (d1, d2, d3) : d1 matrices, each being d2-by-d3.

In [12]:
obj = torch.tensor([[[1,2,3,1],[3,4,1,4],[3,4,1,4]], [[1,2,3,1],[3,4,3,1],[3,4,3,1]]])
print(obj)
obj.shape

tensor([[[1, 2, 3, 1],
         [3, 4, 1, 4],
         [3, 4, 1, 4]],

        [[1, 2, 3, 1],
         [3, 4, 3, 1],
         [3, 4, 3, 1]]])


torch.Size([2, 3, 4])

* If we align all the elements in a single order, the order starts from the very inner bracket. $\rightarrow$ In the above example, it is 1,2,3,1,3,4,1,4, $\cdots$.
* reshape(-1, ~) : -1 means match the size accordingly.
* reshape(-1) : form it as a 1-d array (vector).
* reshape(-1, d1): form it as a 2-d array (matrix), with the 2nd-size=d1.
* reshape(-1, d1, d2): form it as a 3-d array, with the 2nd-size=d1 and 3rd-size=d2.

In [13]:
print(torch.tensor([[1,2],[3,4]]))
print(torch.tensor([[1,2],[3,4]]).reshape(-1)) # a single vector that lines up in the order mentioned above.
print(torch.tensor([[1,2],[3,4]]).reshape(-1,1)) 
print(torch.tensor([[1,2],[3,4]]).reshape(1,-1))

tensor([[1, 2],
        [3, 4]])
tensor([1, 2, 3, 4])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1, 2, 3, 4]])


In [14]:
print(obj)
print(obj.reshape(-1)) # 1-d array
print(obj.reshape(-1, 2)) # 2-d array with 2nd-size=2 (2 columns)
print(obj.reshape(-1,2,3)) # 3-d array with 2nd-size=2, 3rd-size=3 (each matrix having 2-by-3 size.)

tensor([[[1, 2, 3, 1],
         [3, 4, 1, 4],
         [3, 4, 1, 4]],

        [[1, 2, 3, 1],
         [3, 4, 3, 1],
         [3, 4, 3, 1]]])
tensor([1, 2, 3, 1, 3, 4, 1, 4, 3, 4, 1, 4, 1, 2, 3, 1, 3, 4, 3, 1, 3, 4, 3, 1])
tensor([[1, 2],
        [3, 1],
        [3, 4],
        [1, 4],
        [3, 4],
        [1, 4],
        [1, 2],
        [3, 1],
        [3, 4],
        [3, 1],
        [3, 4],
        [3, 1]])
tensor([[[1, 2, 3],
         [1, 3, 4]],

        [[1, 4, 3],
         [4, 1, 4]],

        [[1, 2, 3],
         [1, 3, 4]],

        [[3, 1, 3],
         [4, 3, 1]]])


### Other functionalities

In [15]:
t6=torch.full((3,2),42)
print(t6)

tensor([[42, 42],
        [42, 42],
        [42, 42]])


In [16]:
t7=torch.cat((t3,t6)) # cat = rbind
print(t7)

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])


In [17]:
t8=torch.sin(t7)
print(t8)
t9=t8.reshape(3,2,2)
print(t9)

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])
tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])


### gradient

In [18]:
x=torch.tensor(3.)
w=torch.tensor(4., requires_grad=True) # Only float and complex be applied with gradient, not integers.
b=torch.tensor(5., requires_grad=True)

In [19]:
y=w*x + b # They remember this equation when we obtain the gradient of y w.r.t. other variables.
y

tensor(17., grad_fn=<AddBackward0>)

* If we want to get the gradient, we first need to do y.backward().
* We get an error if we run it twice. We can do it if we redefine y=w*x+b.

In [20]:
y.backward() 
print('dy/dx:',x.grad) # x is a fixed variable, so we cannot differentiate w.r.t. x.
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)
